#!/usr/bin/env ansible-playbook
#---
- hosts: all
  become: yes
  tasks:
        - name: install the 'Development tools' package group
          package: name="@Development tools" state=present
          when:  ansible_distribution == 'CentOS' or
                 ansible_distribution == 'Red Hat Enterprise Linux' or
                 ansible_distribution == 'Fedora'
          become: yes

        - name: Install the 'web-server' meta package group
          package: name="apache2" state=present
          when: ansible_distribution == 'Debian' or
                ansible_distribution == 'Ubuntu'
          become: yes

        - copy:
             src: index.html
             dest: /var/www/html/index.html
             mode: 0644
  handlers:
        - name: restart apache2
          service: name=apache2 state=restarted
        
