---
- hosts: ec2-18-219-10-41.us-east-2.compute.amazonaws.com 
  become: true
  become_user: root 
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
    - name: install packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
       - php
       - php-json
       - php-sqlite3
       - sqlite3
    - name: copying php sample file 
      copy: src=./test.php dest=/var/www/html/sample.php 
